#spring:
#  datasource:#    username: root
#    password: admin
#    url: jdbc:mysql://localhost:3306/crud
#    driver-class-name:
#  jpa:#    show-sql: true
#    hibernate:#      ddl-auto: update
#    properties.hibernate.dialect: org.hibernate.dialect.MySQL55Dialect